config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :new, :create]
  end
  resources :users, only: [:index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users_groups
  has_many :users, through: :users_groups
  has_many :messages
  validates :name, length: { maximum: 10 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :content, presence: true, unless: :img?

  def message_format
    self.created_at.strftime("%Y年%m月%d日 %H時%M分")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, length: { maximum: 10 }
  has_many :users_groups
  has_many :groups, through: :users_groups
  has_many :message
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [ :name]
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit ,:update]

  def index
    @content = Message.all
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成できました。"
    else
      render :new
      #直接viewファイルへ飛ぶ
    end
  end

  def update
    @group.update(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを編集できました。"
    else
      render :new
      #直接viewファイルへ飛ぶ
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path }
        format.json
      end
    else
      redirect_to group_messages_path, alert: "コメントを作成出来ません"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :img).merge(user_id: current_user.id,
      group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update,]

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")

    respond_to do |format|
      format.html
      format.json
   end
  end

  def edit
  end

  def update
    if @user.update(users_params)
      redirect_to root_path, notice: "ユーザー情報を編集しました。"
    else
      flash.now[:alert] = "ユーザー情報を編集できませんでした。"
      render :edit
    end
  end

  private

  def users_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.group__block
  - current_user.groups.each do |group|
    =link_to group_messages_path(group) do #each
      %p.group__block__title
        = group.name
      %p.group__block__text
        - if group.messages.last
          = group.messages.last.content
        - else
          まだメッセージがありません。

app/views/groups/_left.html.haml
/ユーザー名表示
.user
  .user__name
    %p.user__name__item
      = current_user.name
  .user__link
    %ul
      /新規チャットグループ作成
      =link_to new_group_path do
        %li.fa.fa-pencil-square-o
      /アカウント編集
      =link_to edit_user_path(current_user) do
        %li.fa.fa-cog
/グループ表示
.group
  = render partial: "groups/group", locals:{groups: @groups}

app/views/groups/edit.html.haml
= form_for @group do |f|
  .chat-group-form
    %h1 チャットグループ編集
    / %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups/22", :method => "post"}
    .chat-group-form__errors
      - if @group.errors.any?
        %ul
          -@group.errors.full_messages.each do |message|
            %li
            =message
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, placeholder: '新しいグループ名を入力してください', class: 'chat_group_name chat-group-form__input'
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバーを追加
      .chat-group-form__field--right
        = collection_check_boxes(:group,:user_ids, User.all, :id, :name)
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        = f.submit "Save", class: 'chat-group-form__action-btn'
        / %input.chat-group-form__action-btn{"data-disable-with" => "Save", name: "commit", type: "submit", value: "Save"}

app/views/groups/index.html.haml
.contents
  /左側
  .left
    = render partial: "groups/left", locals:{groups: @groups}

app/views/groups/new.html.haml
= form_for(@group) do |f|
  .chat-group-form
    %h1 新規チャットグループ
    #new_chat_group.new_chat_group
      .chat-group-form__errors
      - if @group.errors.any?
        %ul
          -@group.errors.full_messages.each do |message|
            %li
            =message
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{ for: "chat_group_name" } グループ名
        .chat-group-form__field--right
          = f.text_field :name, placeholder: 'グループ名を入力してください', type: 'text', id: 'chat_group_name', class: 'chat-group-form__input'


        .chat-group-form__field--left
          %label.chat-group-form__label{ for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
        .chat-group-form__field--right
          .chat-group-form__search.clearfix
            %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
            #user-search-result

      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
        .chat-group-form__field--right

          #chat-group-users
            #chat-group-user-22.chat-group-user.clearfix
            %input{name: "chat_group[user_ids][]", type: "hidden", value: "22"}
            %p.chat-group-user__name

      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          = f.submit "create", class: 'chat-group-form__action-btn'

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_chat.html.haml
.chat{ "data-message-id": "#{messages.id}"}
  .main__post__name
    = current_user.name
  .main__post__time
    = messages.created_at
  .main__post__text
    = messages.content
  %p.chat__image
    - if messages.img.present?
      = image_tag(messages.img)

app/views/messages/index.html.haml
.contents
  /左側
  .left
    = render partial: "groups/left", locals:{groups: @groups}
  /右側
  .right
    /グループ名表示箇所
    .header
      .header__block
        .header__block__title
          = @group.name
        .header__block__member MEMBER: TestTarou
      .header__edit
        =link_to "Edit", root_path, class: "header__edit__text"
    /チャット表示箇所
    .main
      - @messages.each do |message|
        .main__post{'data-id': message.id}
          .main__post__name
            = current_user.name
          .main__post__time
            = message.message_format
          .main__post__text
            = message.content

    /入力箇所
    .footer
      = form_for [@group,@message] do |f|
        .footer__inner
          .footer__inner__form
            .footer__inner__form__block
              = f.text_area :content, placeholder: "type a message", class:'footer__inner__form__block__btn textbox"'
              = f.label :img, class:'footer__inner__form__icon' do
                %i.fa.fa-picture-o
                  = f.file_field :img, class:"hidden"
          .footer__inner__send
            = f.submit value: "Send", class:'footer__inner__send__btn'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(@user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'